services:
  - type: web
    name: nanopdf
    env: python
    buildCommand: |
      apt-get update && apt-get install -y ghostscript
      pip install -r requirements.txt
    startCommand: gunicorn app:app
